// ============================================================
// HARDBALL - game logic (extracted to js/game.js)
// ============================================================

// ---- Question bank (matches promptukit `sections` schema) ----
// Embedded so the game works from file:// with no CORS headaches.
// You can later swap this out for `fetch("questions.json")` and
// point it at anything generated by `promptukit question-bank`.
const EMBEDDED_QUESTION_BANK = {
  "title": "Hardball Default Bank",
  "sections": [
    {
      "title": "General Knowledge",
      "questions": [
        {"prompt": "Which planet has the most moons?", "choices": ["Jupiter", "Saturn", "Uranus", "Neptune"], "answer": 1, "difficulty": "medium"},
        {"prompt": "What is the capital of Australia?", "choices": ["Sydney", "Melbourne", "Canberra", "Perth"], "answer": 2, "difficulty": "easy"},
        {"prompt": "How many bones are in the adult human body?", "choices": ["186", "206", "226", "246"], "answer": 1, "difficulty": "medium"},
        {"prompt": "What is the largest ocean on Earth?", "choices": ["Atlantic", "Indian", "Arctic", "Pacific"], "answer": 3, "difficulty": "easy"},
        {"prompt": "Which element has the chemical symbol 'Au'?", "choices": ["Silver", "Gold", "Aluminum", "Argon"], "answer": 1, "difficulty": "easy"}
      ]
    },
    {
      "title": "Science & Engineering",
      "questions": [
        {"prompt": "What does a Pareto frontier represent?", "choices": ["The worst solutions", "Solutions where no objective can improve without worsening another", "The average of all solutions", "Solutions that satisfy all constraints"], "answer": 1, "difficulty": "hard"},
        {"prompt": "The unit of electrical resistance is the...", "choices": ["Volt", "Watt", "Ohm", "Ampere"], "answer": 2, "difficulty": "easy"},
        {"prompt": "Approximately what percent of Earth's freshwater is in glaciers and ice caps?", "choices": ["10%", "30%", "50%", "68%"], "answer": 3, "difficulty": "hard"},
        {"prompt": "What does 'riparian' refer to?", "choices": ["Desert ecosystems", "Areas along rivers and streams", "Deep ocean zones", "Mountain peaks"], "answer": 1, "difficulty": "medium"},
        {"prompt": "Speed of light in a vacuum (m/s) is closest to...", "choices": ["3 × 10⁸", "3 × 10⁶", "3 × 10¹⁰", "3 × 10⁴"], "answer": 0, "difficulty": "medium"}
      ]
    },
    {
      "title": "Film, TV & Music",
      "questions": [
        {"prompt": "Who directed 'Spirited Away' and 'Ponyo'?", "choices": ["Isao Takahata", "Mamoru Hosoda", "Hayao Miyazaki", "Makoto Shinkai"], "answer": 2, "difficulty": "easy"},
        {"prompt": "Bob Dylan's birth name is...", "choices": ["Robert Allen Zimmerman", "Robert James Dylan", "Robert Thomas Allen", "Robert Alan Wilson"], "answer": 0, "difficulty": "medium"},
        {"prompt": "Which album contains 'Born to Run'?", "choices": ["Nebraska", "Born to Run", "The River", "Darkness on the Edge of Town"], "answer": 1, "difficulty": "easy"},
        {"prompt": "Bad Bunny's summer 2022 album was titled...", "choices": ["YHLQMDLG", "Un Verano Sin Ti", "El Último Tour del Mundo", "X 100pre"], "answer": 1, "difficulty": "medium"},
        {"prompt": "Which band did Bob Mould co-found in the 1980s?", "choices": ["Sugar", "Hüsker Dü", "The Replacements", "Dinosaur Jr."], "answer": 1, "difficulty": "hard"}
      ]
    },
    {
      "title": "Motorsport",
      "questions": [
        {"prompt": "How many laps is the Indianapolis 500?", "choices": ["100", "150", "200", "250"], "answer": 2, "difficulty": "easy"},
        {"prompt": "Modern F1 cars use which engine formula?", "choices": ["1.6L V6 hybrid turbo", "3.0L V10", "2.4L V8", "1.5L I4 turbo"], "answer": 0, "difficulty": "medium"},
        {"prompt": "IndyCar's crown-jewel oval race is held at...", "choices": ["Texas Motor Speedway", "Indianapolis Motor Speedway", "Iowa Speedway", "Gateway"], "answer": 1, "difficulty": "easy"},
        {"prompt": "DRS in Formula 1 stands for...", "choices": ["Dynamic Racing System", "Drag Reduction System", "Downforce Recovery System", "Direct Response Steering"], "answer": 1, "difficulty": "medium"}
      ]
    }
  ]
};

// Try to load a remote question bank (fallback to embedded).
const REMOTE_BANK_URL = "http://127.0.0.1:8000/trivia";

// Start with the embedded bank; we'll attempt to load a remote bank below.
let QUESTION_BANK = EMBEDDED_QUESTION_BANK;
let remoteBankReady; // promise that resolves when the remote-bank attempt settles (success or failure)

// ---- Normalize: flatten to a single question pool, promptukit-style tolerant ----
function flattenBank(bank) {
  const pool = [];
  if (Array.isArray(bank.questions)) {
    // Server format: { questions: [...], categories: [...strings] }
    for (const q of bank.questions) {
      pool.push(normalizeQuestion(q, q.category || "Questions"));
    }
  } else if (Array.isArray(bank)) {
    for (const q of bank) pool.push(normalizeQuestion(q, q.category || "Questions"));
  } else {
    // Promptukit sections format: { sections: [{title, questions}] }
    // Only treat bank.categories as sections if its items are objects (not strings)
    const cats = bank.categories;
    const sections = bank.sections || (Array.isArray(cats) && cats[0] && typeof cats[0] === 'object' ? cats : []);
    for (const sec of sections) {
      const title = sec.title || sec.name || sec.label || "Questions";
      for (const q of (sec.questions || [])) {
        pool.push(normalizeQuestion(q, title));
      }
    }
  }
  return pool;
}

function normalizeQuestion(q, category) {
  return {
    prompt: q.prompt || q.q || q.question || q.text || "???",
    choices: q.choices || q.answers || [],
    answer: q.answer ?? q.correct ?? q.correct_index ?? 0,
    difficulty: q.difficulty || "medium",
    category
  };
}

let POOL = flattenBank(QUESTION_BANK);

// ---- Seeded randomness / sampling without replacement ----
// These variables/backing structures implement sampling-without-replacement
// using a seeded RNG + Fisher-Yates shuffle. We seed from the URL (?seed=123)
// when present, otherwise from `Date.now()` so each session differs.
let RNG_SEED = null;
let RNG = null;
let SHUFFLED_INDICES = null;
let SHUFFLED_CURSOR = 0;
let GAME_POOL = []; // snapshot of POOL at game start; immutable during a session

function prepareShuffledPool(seedOverride) {
  const params = new URLSearchParams(location.search);
  let seedParam = typeof seedOverride !== 'undefined' ? seedOverride : params.get('seed');
  let seed;
  if (seedParam != null) {
    const parsed = Number.parseInt(String(seedParam), 10);
    if (!Number.isFinite(parsed) || isNaN(parsed)) {
      seed = Utils.xfnv1a(String(seedParam));
    } else {
      seed = parsed;
    }
  } else {
    // Use full ms timestamp — >>> 0 would truncate to 32-bit, collapsing many timestamps to the same seed
    seed = Date.now();
  }

  GAME_POOL = POOL.slice(); // snapshot pool so remote-bank loads don't affect this session
  RNG_SEED = seed;
  RNG = Utils.createRng(RNG_SEED);
  SHUFFLED_INDICES = Array.from({ length: GAME_POOL.length }, (_, i) => i);
  Utils.seededShuffle(SHUFFLED_INDICES, RNG);
  SHUFFLED_CURSOR = 0;
  console.log("Prepared shuffled pool — seed:", RNG_SEED, "GAME_POOL.length:", GAME_POOL.length, "SHUFFLED_INDICES.length:", SHUFFLED_INDICES.length, "SHUFFLED_CURSOR:", SHUFFLED_CURSOR);
  if (typeof els !== 'undefined' && els.status) els.status.textContent = `Seed: ${RNG_SEED}`;
}

// ---- Game state ----
const ROUND_TYPES = ["buzz", "simul", "strikes"];
const ROUND_LABELS = { buzz: "BUZZ-IN", simul: "SIMULTANEOUS", strikes: "THREE STRIKES" };

const state = {
  totalRounds: 5,
  round: 0,
  roundType: "buzz",
  question: null,
  players: [
    { id: 1, cash: 0, leverage: 0, strikes: 0, lockedOut: false, pickedChoice: null, answeredCorrect: false, strikesThisRound: 0, isHuman: false },
    { id: 2, cash: 0, leverage: 0, strikes: 0, lockedOut: false, pickedChoice: null, answeredCorrect: false, strikesThisRound: 0, isHuman: false }
  ],
  phase: "idle",     // idle | question | deal | between
  roundQuestions: 0,
  usedQuestions: new Set(),
  roundStart: 0,
  timerTotalMs: 12000,
  timerTimeout: null,
  aiTimers: [],
  firstCorrectPlayer: null,
  briefcaseValue: 0,
  warningTimeout: null
};

// ---- DOM refs ----
const $ = (id) => document.getElementById(id);
const els = {
  title: $("scene-title"),
  game: $("scene-game"),
  prompt: $("question-prompt"),
  choices: $("choices"),
  roundNum: $("round-num"),
  roundTotal: $("round-total"),
  roundType: $("round-type"),
  sectionTitle: $("section-title"),
  timerFill: $("timer-fill"),
  modal: $("modal-backdrop"),
  modalTitle: $("modal-title"),
  modalSub: $("modal-subtitle"),
  modalDetail: $("modal-detail"),
  modalActions: $("modal-actions"),
  handP1: $("hand-p1"),
  handP2: $("hand-p2"),
  briefcase: $("briefcase"),
  dealBanner: $("deal-banner"),
  dealBannerText: $("deal-banner-text"),
  dealArea: $("deal-area"),
  status: $("status-left"),
  statusRight: $("status-right"),
  panelP1: $("panel-p1"),
  panelP2: $("panel-p2"),
  briefcaseAmount: $("briefcase-amount")
};

// Attempt to load remote bank now that `els` is initialized
function tryLoadRemoteBank() {
  remoteBankReady = (async () => {
  try {
    if (els && els.status) els.status.textContent = `Loading question bank…`;
    if (els && els.statusRight) els.statusRight.textContent = `Bank: loading…`;
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 5000);
    const res = await fetch(REMOTE_BANK_URL, { signal: controller.signal, cache: "no-store" });
    clearTimeout(timeoutId);
    if (!res.ok) throw new Error("HTTP " + res.status);

    // Capture raw response text and headers for diagnostics (helps identify shape mismatches)
    const contentType = res.headers.get('content-type') || '';
    const rawText = await res.clone().text();
    let data = null;
    try {
      data = JSON.parse(rawText);
    } catch (parseErr) {
      // Fallback: try res.json() in case clone/text altered stream behavior
      try {
        data = await res.json();
      } catch (jsonErr) {
        console.warn('Failed to parse remote bank JSON', parseErr, jsonErr);
        console.debug('Remote /trivia raw snippet:', rawText.slice(0, 800));
        throw new Error('Invalid JSON from remote bank');
      }
    }

    // Log a concise summary of the fetched payload so you can inspect exact keys/shape
    try {
      const summary = {
        url: REMOTE_BANK_URL,
        status: res.status,
        contentType,
        rawLength: rawText.length,
        isArray: Array.isArray(data),
        topKeys: data && typeof data === 'object' ? Object.keys(data).slice(0, 10) : null
      };
      console.debug('Remote bank fetched:', summary);
      if (data && typeof data === 'object' && data.sections) {
        console.debug('Remote bank sections:', data.sections.map(s => ({ title: s.title || s.name || '(unnamed)', questions: (s.questions || []).length })));
      }

    } catch (e) {
      console.warn('Failed logging remote bank summary', e);
    }

    if (data && typeof data === 'object') {
      QUESTION_BANK = data;
      POOL = flattenBank(QUESTION_BANK);
      if (!Array.isArray(POOL) || POOL.length === 0) {
        console.warn("Remote question bank contained no questions — falling back to embedded bank.");
        console.debug('Remote bank sample snippet:', JSON.stringify(data && (Array.isArray(data) ? data.slice(0,3) : { keys: Object.keys(data).slice(0,10) }), null, 2));
        QUESTION_BANK = EMBEDDED_QUESTION_BANK;
        POOL = flattenBank(QUESTION_BANK);
        if (els && els.statusRight) els.statusRight.textContent = "Bank: embedded (remote empty)";
        if (els && els.status) els.status.textContent = "Ready.";
      } else {
        const label = QUESTION_BANK.title || 'remote';
        if (els && els.statusRight) els.statusRight.textContent = `Bank: ${label} (${POOL.length} Qs)`;
        if (els && els.status) els.status.textContent = "Ready.";
        console.log("Loaded question bank from remote:", REMOTE_BANK_URL);
      }
      // POOL is now updated; GAME_POOL will be snapshotted on next startGame() call.
      // Do NOT reshuffle here — that would corrupt any in-progress game session.
    } else {
      throw new Error("Invalid JSON from remote bank");
    }
  } catch (err) {
    console.warn("Remote question bank not available:", err);
    if (els && els.statusRight) els.statusRight.textContent = "Bank: embedded (offline)";
    if (els && els.status) els.status.textContent = "Ready.";
  }
  })();
}
tryLoadRemoteBank();

// ============================================================
// SETUP
// ============================================================
$("btn-start").addEventListener("click", startGame);
$("btn-reload-bank").addEventListener("click", tryLoadRemoteBank);
$("btn-rounds-3").addEventListener("click", () => setRounds(3));
$("btn-rounds-5").addEventListener("click", () => setRounds(5));
$("btn-rounds-7").addEventListener("click", () => setRounds(7));
$("btn-help").addEventListener("click", showHelpModal);
const menubarHelp = $("menubar-help");
if (menubarHelp) menubarHelp.addEventListener("click", showHelpModal);

// --- Join UI helpers: controller "Y" will mark a gamepad as joined (human)
function updateJoinUI() {
  for (let i = 0; i < 2; i++) {
    const btn = $("join-p" + (i + 1));
    if (!btn) continue;
    if (state.players[i].isHuman) {
      btn.textContent = `P${i + 1}: HUMAN`;
      btn.classList.add('primary');
    } else {
      btn.textContent = `P${i + 1}: CPU (Press Y to join)`;
      btn.classList.remove('primary');
    }
  }
}

function joinPlayer(playerNum) {
  const idx = playerNum - 1;
  if (!state.players[idx]) return;
  if (state.players[idx].isHuman) return; // already joined
  state.players[idx].isHuman = true;
  updateJoinUI();
  if (els.status) els.status.textContent = `Player ${playerNum} joined (controller ${playerNum}).`;
}

// Allow clicking the join buttons to toggle CPU/Human locally
const jb1 = $("join-p1");
if (jb1) jb1.addEventListener('click', () => { state.players[0].isHuman = !state.players[0].isHuman; updateJoinUI(); });
const jb2 = $("join-p2");
if (jb2) jb2.addEventListener('click', () => { state.players[1].isHuman = !state.players[1].isHuman; updateJoinUI(); });

// Initialize join UI (default: CPU if nobody presses Y)
updateJoinUI();

function setRounds(n) {
  state.totalRounds = n;
  $("round-count-label").textContent = `Playing best of ${n} rounds`;
}

async function startGame() {
  // Block until the remote-bank attempt settles so POOL is final before we snapshot it
  if (remoteBankReady) {
    if (els && els.status) els.status.textContent = "Loading question bank…";
    await remoteBankReady;
  }
  state.round = 0;
  // Prepare seeded shuffled pool for this session (seeded from URL or Date.now())
  prepareShuffledPool();
  // Keep usedQuestions cleared for compatibility
  if (state.usedQuestions && state.usedQuestions.clear) state.usedQuestions.clear();
  for (const p of state.players) {
    p.cash = 0; p.leverage = 0; p.strikes = 0; p.lockedOut = false;
  }
  updateHUD();
  showScene("game");
  nextRound();
}

function showScene(name) {
  document.querySelectorAll(".scene").forEach(s => s.classList.remove("active"));
  $("scene-" + name).classList.add("active");
  if (name === "title") {
    titleFocus = titleFocus || 0;
    updateTitleFocus();
  } else {
    document.querySelectorAll('.luna-btn.focused').forEach(b => b.classList.remove('focused'));
  }
}

// ============================================================
// ROUND FLOW
// ============================================================
function nextRound() {
  if (state.round >= state.totalRounds) {
    return endGame();
  }
  state.round++;
  state.roundType = ROUND_TYPES[(state.round - 1) % ROUND_TYPES.length];
  const base = 100 + state.round * 60;
  state.briefcaseValue = base + Math.floor(Math.random() * 5) * 25;
  state.roundQuestions = 1;
  // Pick a question not yet used (sampling without replacement via shuffled indices)
  let q = randomQuestion();
  if (!q) {
    console.error('nextRound: randomQuestion returned undefined', { GAME_POOL_length: GAME_POOL.length, SHUFFLED_length: (Array.isArray(SHUFFLED_INDICES) ? SHUFFLED_INDICES.length : 0), SHUFFLED_CURSOR });
    q = { prompt: 'No question available', choices: ['OK'], answer: 0, difficulty: 'easy', category: 'System' };
  }
  state.question = q;
  // Reset per-round player state
  for (const p of state.players) {
    p.leverage = 0;
    p.pickedChoice = null;
    p.answeredCorrect = false;
    p.lockedOut = false;
    p.strikesThisRound = 0;
  }
  state.firstCorrectPlayer = null;

  // Update UI labels
  els.roundNum.textContent = state.round;
  els.roundTotal.textContent = state.totalRounds;
  els.roundType.textContent = roundTypeLabel();
  els.sectionTitle.textContent = q.category;
  updateHUD();
  resetDealScene();

  showModal({
    title: "ROUND " + state.round,
    subtitle: ROUND_LABELS[state.roundType] + "  —  BRIEFCASE: $" + state.briefcaseValue,
    detail: roundTypeBlurb(state.roundType),
    actions: [{ label: "▶ Begin", primary: true, onclick: () => { hideModal(); beginQuestion(); } }]
  });
}

function roundTypeLabel() {
  const maxQ = state.roundType === "strikes" ? 27 : 10;
  return `${ROUND_LABELS[state.roundType]} (${state.roundQuestions}/${maxQ})`;
}

function roundTypeBlurb(t) {
  if (t === "buzz") return "First correct answer wins ALL the leverage. Wrong answer = lockout.";
  if (t === "simul") return "Lock in your answer secretly. Both reveal together. Correct answers split leverage.";
  if (t === "strikes") return "Series of rapid questions — wrong answer = strike. Round continues until a player reaches 3 strikes (locked out). A correct answer removes one of your strikes.";
  return "";
}

function randomQuestion() {
  if (!Array.isArray(GAME_POOL) || GAME_POOL.length === 0) {
    console.error("Question pool is empty — falling back to embedded bank.");
    QUESTION_BANK = EMBEDDED_QUESTION_BANK;
    POOL = flattenBank(QUESTION_BANK);
    prepareShuffledPool();
    if (!Array.isArray(GAME_POOL) || GAME_POOL.length === 0) {
      return { prompt: 'No questions available', choices: ['OK'], answer: 0, difficulty: 'easy', category: 'System' };
    }
  }
  // Reshuffle only when all questions have been drawn (sampling without replacement cycles)
  if (!SHUFFLED_INDICES || SHUFFLED_CURSOR >= SHUFFLED_INDICES.length) {
    const newSeed = (RNG_SEED + Date.now()) >>> 0;
    RNG_SEED = newSeed;
    RNG = Utils.createRng(RNG_SEED);
    SHUFFLED_INDICES = Array.from({ length: GAME_POOL.length }, (_, i) => i);
    Utils.seededShuffle(SHUFFLED_INDICES, RNG);
    SHUFFLED_CURSOR = 0;
  }
  const idx = SHUFFLED_INDICES[SHUFFLED_CURSOR++];
  return GAME_POOL[idx];
}

function beginQuestion() {
  state.phase = "question";
  renderChoices();
  els.prompt.textContent = state.question.prompt;
  startTimer(state.timerTotalMs);
  // Schedule AI actions for CPU-controlled players (if any)
  scheduleAIForQuestion();
  els.status.textContent = "Phase: answering...";
}

function renderChoices() {
  els.choices.innerHTML = "";
  // Display letters that match Xbox face layout: Y (top), X (left), B (right), A (bottom)
  const displayLetters = ["Y", "X", "B", "A"];
  const posClass = ["pos-y", "pos-x", "pos-b", "pos-a"];
  state.question.choices.forEach((ch, i) => {
    const div = document.createElement("div");
    div.className = "choice";
    div.classList.add(posClass[i] || "");
    div.dataset.index = i;
    div.setAttribute('role', 'button');
    div.setAttribute('aria-label', `${displayLetters[i] || ''}: ${ch}`);
    div.innerHTML = `
        <div class="letter">${displayLetters[i] || ''}</div>
        <div class="text">${escapeHTML(ch)}</div>
        <div class="press-indicators">
          <div class="press-dot p1" data-player="1"></div>
          <div class="press-dot p2" data-player="2"></div>
        </div>
      `;
    // Allow mouse/touch selection still
    div.addEventListener('click', () => handlePlayerInput(1, i));
    els.choices.appendChild(div);
  });
}

function escapeHTML(s) {
  const d = document.createElement("div");
  d.textContent = s;
  return d.innerHTML;
}

// ============================================================
// TIMER
// ============================================================
function startTimer(ms) {
  if (state.warningTimeout) { clearTimeout(state.warningTimeout); state.warningTimeout = null; }
  state.roundStart = performance.now();
  els.timerFill.style.transition = "none";
  els.timerFill.style.width = "100%";
  els.timerFill.classList.remove("warning");
  // Force reflow
  void els.timerFill.offsetWidth;
  els.timerFill.style.transition = `width ${ms}ms linear`;
  els.timerFill.style.width = "0%";

  clearTimeout(state.timerTimeout);
  state.timerTimeout = setTimeout(() => onTimeUp(), ms);

  state.warningTimeout = setTimeout(() => {
    state.warningTimeout = null;
    els.timerFill.classList.add("warning");
  }, ms * 0.75);
}

function stopTimer() {
  clearTimeout(state.timerTimeout);
  if (state.warningTimeout) { clearTimeout(state.warningTimeout); state.warningTimeout = null; }
  // Clear any scheduled AI timeouts for this question
  if (state.aiTimers && state.aiTimers.length) {
    state.aiTimers.forEach(t => clearTimeout(t));
    state.aiTimers = [];
  }
  // Freeze the bar where it is by computing the current width
  const rect = els.timerFill.getBoundingClientRect();
  const parentRect = els.timerFill.parentElement.getBoundingClientRect();
  const currentPct = (rect.width / parentRect.width) * 100;
  els.timerFill.style.transition = "none";
  els.timerFill.style.width = currentPct + "%";
}

// ============================================================
// SIMPLE AI OPPONENT (runs when a player slot is not marked human)
// ============================================================
function scheduleAIForQuestion() {
  // Clear any previous AI timers
  state.aiTimers = state.aiTimers || [];
  state.aiTimers.forEach(t => clearTimeout(t));
  state.aiTimers = [];
  if (state.phase !== 'question') return;
  const q = state.question;
  if (!q) return;

  for (let i = 0; i < state.players.length; i++) {
    const p = state.players[i];
    const playerNum = i + 1;
    if (p.isHuman) continue; // humans supply their own input

    const difficulty = (q.difficulty || 'medium').toLowerCase();
    let baseAcc = difficulty === 'easy' ? 0.8 : (difficulty === 'hard' ? 0.4 : 0.6);
    if (state.roundType === 'strikes') {
      if (p.strikes >= 2) baseAcc = Math.min(0.95, baseAcc + 0.15);
    }
    baseAcc = Math.max(0.05, Math.min(0.95, baseAcc));

    const willBeCorrect = Math.random() < baseAcc;
    let chosenIdx;
    if (willBeCorrect) chosenIdx = q.answer;
    else {
      const wrong = [];
      for (let j = 0; j < q.choices.length; j++) if (j !== q.answer) wrong.push(j);
      chosenIdx = wrong[Math.floor(Math.random() * wrong.length)];
    }

    let rt;
    if (state.roundType === 'buzz') {
      rt = 900 + Math.random() * 1400 * (1 - baseAcc * 0.4);
    } else {
      const max = Math.max(300, state.timerTotalMs - 400);
      rt = 300 + Math.random() * Math.max(0, max - 300);
    }

    const tid = setTimeout(() => {
      if (state.phase !== 'question') return;
      if (state.players[i].lockedOut || state.players[i].isHuman) return;
      handlePlayerInput(playerNum, chosenIdx);
    }, rt);
    state.aiTimers.push(tid);
  }
}

function onTimeUp() {
  if (state.phase !== "question") return;
  // Resolve based on round type
  resolveQuestion();
}

// ============================================================
// INPUT (keyboard + gamepad)
// ============================================================
// P1: 1/2/3/4 -> indices 0-3
// P2: 7/8/9/0 -> indices 0-3
const KEY_MAP = {
  "1": { player: 1, idx: 0 }, "2": { player: 1, idx: 1 },
  "3": { player: 1, idx: 2 }, "4": { player: 1, idx: 3 },
  "7": { player: 2, idx: 0 }, "8": { player: 2, idx: 1 },
  "9": { player: 2, idx: 2 }, "0": { player: 2, idx: 3 }
};

document.addEventListener("keydown", (e) => {
  if (e.repeat) return;
  const m = KEY_MAP[e.key];
  if (m && state.phase === "question") {
    if (state.players[m.player - 1].isHuman) {
      handlePlayerInput(m.player, m.idx);
    }
  }
  if (e.key === "Escape" && state.phase !== "idle") {
    // Quick reset shortcut
    showScene("title");
    state.phase = "idle";
  }
});

// Gamepad handling with explicit Xbox layout mapping and title navigation
// Xbox gamepad standard mapping: 0=A, 1=B, 2=X, 3=Y
// We remap so that controller face buttons map to choice positions:
// button 3 (Y) -> choice 0 (top), 2 (X) -> choice 1 (left), 1 (B) -> choice 2 (right), 0 (A) -> choice 3 (bottom)
const GAMEPAD_BUTTON_TO_CHOICE = [3, 2, 1, 0]; // gamepad button idx -> choice idx
const gamepadPrev = {};

// Title screen navigation elements
const TITLE_NAV_ELEMENTS = [ $("btn-start"), $("btn-rounds-3"), $("btn-rounds-5"), $("btn-rounds-7") ];
let titleFocus = 0;
function updateTitleFocus() {
  TITLE_NAV_ELEMENTS.forEach((el, i) => {
    if (!el) return;
    el.classList.toggle('focused', i === titleFocus);
  });
}
function handleTitleGamepadInput(player, buttonIndex) {
  // D-pad: 14=left, 15=right; A (0) = confirm
  if (buttonIndex === 14) {
    titleFocus = (titleFocus - 1 + TITLE_NAV_ELEMENTS.length) % TITLE_NAV_ELEMENTS.length;
    updateTitleFocus();
  } else if (buttonIndex === 15) {
    titleFocus = (titleFocus + 1) % TITLE_NAV_ELEMENTS.length;
    updateTitleFocus();
  } else if (buttonIndex === 0) {
    const el = TITLE_NAV_ELEMENTS[titleFocus];
    if (el) el.click();
  }
}

// Modal focus for controller confirmation
let modalFocus = 0;
function updateModalFocus() {
  if (!els.modalActions) return;
  const btns = els.modalActions.querySelectorAll('button');
  btns.forEach((b, i) => b.classList.toggle('focused', i === modalFocus));
}

function pollGamepads() {
  const pads = navigator.getGamepads ? navigator.getGamepads() : [];
  for (let p = 0; p < Math.min(2, pads.length); p++) {
    const pad = pads[p];
    if (!pad) continue;
    const player = p + 1;
    const prev = gamepadPrev[player] || (gamepadPrev[player] = []);

    // Face buttons 0..3 (A,B,X,Y)
    for (const b of [0,1,2,3]) {
      const pressed = pad.buttons[b] && pad.buttons[b].pressed;
      if (pressed && !prev[b]) {
        // Modal gets priority when active
        if (els.modal && els.modal.classList.contains('active')) {
          // A (0) confirms currently focused modal action
          if (b === 0) {
            const btns = els.modalActions.querySelectorAll('button');
            const btn = btns[modalFocus] || btns[0];
            if (btn) btn.click();
          }
        } else if (document.querySelector("#scene-title").classList.contains("active")) {
            // On the title screen: pressing Y (button 3) joins that controller's player slot
            if (b === 3 && !state.players[player - 1].isHuman) {
              joinPlayer(player);
            } else {
              handleTitleGamepadInput(player, b);
            }
        } else if (state.phase === "question") {
          // Only accept gamepad input if this player slot is human
          if (state.players[player - 1] && state.players[player - 1].isHuman) {
            const choiceIdx = GAMEPAD_BUTTON_TO_CHOICE[b];
            handlePlayerInput(player, choiceIdx);
          }
        }
      }
      prev[b] = !!pressed;
    }

    // D-pad (12=up,13=down,14=left,15=right) for title/modal navigation
    for (const b of [12,13,14,15]) {
      const pressed = pad.buttons[b] && pad.buttons[b].pressed;
      if (pressed && !prev[b]) {
        if (els.modal && els.modal.classList.contains('active')) {
          // left/right to change modal focus
          const btns = els.modalActions ? els.modalActions.children : null;
          if (btns && btns.length) {
            if (b === 14) {
              modalFocus = (modalFocus - 1 + btns.length) % btns.length;
              updateModalFocus();
            } else if (b === 15) {
              modalFocus = (modalFocus + 1) % btns.length;
              updateModalFocus();
            }
          }
        } else if (document.querySelector("#scene-title").classList.contains("active")) {
          handleTitleGamepadInput(player, b);
        }
      }
      prev[b] = !!pressed;
    }
  }
  requestAnimationFrame(pollGamepads);
}
// Initialize title focus if title is visible
if (document.querySelector("#scene-title").classList.contains("active")) updateTitleFocus();
requestAnimationFrame(pollGamepads);

function handlePlayerInput(playerNum, choiceIdx) {
  if (choiceIdx >= state.question.choices.length) return;
  const p = state.players[playerNum - 1];
  if (p.lockedOut) return;

  // Round-type-specific input handling
  if (state.roundType === "buzz") {
    // first correct answer takes it all; wrong answer locks you out
    if (p.pickedChoice !== null) return; // one shot
    p.pickedChoice = choiceIdx;
    markPress(playerNum, choiceIdx);
    const correct = choiceIdx === state.question.answer;
    if (correct) {
      state.firstCorrectPlayer = playerNum;
      p.answeredCorrect = true;
      stopTimer();
      state.phase = "resolving"; // block further input immediately
      setTimeout(() => resolveQuestion(), 300);
    } else {
      // Wrong buzz = lockout for this question
      p.lockedOut = true;
      flashChoice(choiceIdx, "incorrect");
      // Other player still has a chance
      checkBothLockedOrAnswered();
    }
  } else if (state.roundType === "simul") {
    // Can change pick until time runs out; keep picks secret until reveal
    p.pickedChoice = choiceIdx;
    // Do NOT show press indicators here so picks remain hidden during simultaneous lock-in.
    // If both players have locked in, speed up to reveal both at the same time.
    if (state.players[0].pickedChoice !== null && state.players[1].pickedChoice !== null) {
      stopTimer();
      state.phase = "resolving";
      setTimeout(() => resolveQuestion(), 500);
    }
  } else if (state.roundType === "strikes") {
    // Each wrong answer is a strike (this round). Right answer reverses opponent's strike (if any).
    if (p.pickedChoice === choiceIdx) return; // avoid spam on same choice
    p.pickedChoice = choiceIdx;
    markPress(playerNum, choiceIdx);
    const correct = choiceIdx === state.question.answer;
    if (correct) {
      p.answeredCorrect = true;
      stopTimer();
      state.phase = "resolving";
      setTimeout(() => resolveQuestion(), 400);
    } else {
      p.strikesThisRound++;
      flashChoice(choiceIdx, "incorrect");
      // Total strikes including this round
      const totalStrikes = p.strikes + p.strikesThisRound;
      if (totalStrikes >= 3) {
        p.lockedOut = true;
      }
      updateHUD();
      // Reset pick so they can try again (if not locked out)
      setTimeout(() => { p.pickedChoice = null; clearPress(playerNum); }, 400);
      checkBothLockedOrAnswered();
    }
  }
}

function checkBothLockedOrAnswered() {
  const both = state.players.every(p => p.lockedOut || p.answeredCorrect);
  if (both && state.phase === "question") {
    stopTimer();
    state.phase = "resolving";
    setTimeout(() => resolveQuestion(), 400);
  }
}

function markPress(playerNum, idx) {
  clearPress(playerNum);
  const choice = els.choices.children[idx];
  if (!choice) return;
  const dot = choice.querySelector(`.press-dot.p${playerNum}`);
  if (dot) dot.classList.add("shown");
}
function clearPress(playerNum) {
  document.querySelectorAll(`.press-dot.p${playerNum}`).forEach(d => d.classList.remove("shown"));
}
function updateAllPressIndicators() {
  clearPress(1); clearPress(2);
  for (const p of state.players) {
    if (p.pickedChoice !== null) markPress(p.id, p.pickedChoice);
  }
}
function flashChoice(idx, cls) {
  const el = els.choices.children[idx];
  if (!el) return;
  el.classList.add(cls);
  setTimeout(() => el.classList.remove(cls), 600);
}

// ============================================================
// RESOLUTION
// ============================================================
function resolveQuestion() {
  if (state.phase !== "question" && state.phase !== "resolving") return;
  state.phase = "deal";
  stopTimer();

  const correct = state.question.answer;
  // Show the correct answer
  for (let i = 0; i < els.choices.children.length; i++) {
    els.choices.children[i].classList.remove("incorrect");
  }
  els.choices.children[correct].classList.add("correct");

  // Reveal any secret picks (simultaneous rounds) by showing press indicators now
  if (state.roundType === "simul") {
    updateAllPressIndicators();
  }

  // Compute leverage per round type (incremental — accumulates across questions in a round)
  if (state.roundType === "buzz") {
    if (state.firstCorrectPlayer) {
      state.players[state.firstCorrectPlayer - 1].leverage += 50;
    }
    for (const p of state.players) {
      if (p.lockedOut && !p.answeredCorrect) p.leverage -= 20;
    }
  } else if (state.roundType === "simul") {
    for (const p of state.players) {
      if (p.pickedChoice === correct) {
        p.answeredCorrect = true;
        p.leverage += 30;
      } else if (p.pickedChoice === null) {
        p.leverage -= 20;
      } else {
        p.leverage -= 10;
      }
    }
  } else if (state.roundType === "strikes") {
    // Commit strikesThisRound to total
    for (const p of state.players) {
      p.strikes = Math.min(3, p.strikes + p.strikesThisRound);
    }
    for (let i = 0; i < 2; i++) {
      const p = state.players[i];
      if (p.answeredCorrect) {
        p.leverage += 35;
        if (p.strikes > 0) p.strikes--;
      } else if (p.lockedOut) {
        p.leverage -= 25;
      } else {
        p.leverage -= 5;
      }
    }
  }

  updateHUD();
  els.status.textContent = "Phase: negotiating...";

  setTimeout(() => runDealPhase(), 900);
}

// ============================================================
// DEAL PHASE - the hand-shove animation
// ============================================================
function resetDealScene() {
  els.handP1.style.left = "2%";
  els.handP1.style.transform = "";
  els.handP2.style.right = "2%";
  els.handP2.style.transform = "scaleX(-1)";
  els.briefcase.style.transform = "translateX(-50%)";
  els.dealBanner.classList.remove("shown");
  if (els.briefcaseAmount && state.briefcaseValue) {
    els.briefcaseAmount.textContent = "$" + state.briefcaseValue;
  }
}

function startNextQuestionSameRound() {
  state.roundQuestions++;
  const q = randomQuestion();
  state.question = q;
  for (const p of state.players) {
    p.pickedChoice = null;
    p.answeredCorrect = false;
    p.strikesThisRound = 0;
    p.lockedOut = (state.roundType === "strikes") ? (p.strikes >= 3) : false;
  }
  state.firstCorrectPlayer = null;
  els.sectionTitle.textContent = q.category;
  els.roundType.textContent = roundTypeLabel();
  els.prompt.textContent = q.prompt;
  renderChoices();
  // Show a "ready" timer state during the reading window so it's clear the clock hasn't started
  els.timerFill.style.transition = "none";
  els.timerFill.style.width = "100%";
  els.timerFill.classList.remove("warning");
  setTimeout(() => beginQuestion(), 3000);
}

function runDealPhase() {
  // Compute who "wins the deal" based on leverage
  const p1 = state.players[0];
  const p2 = state.players[1];
  const diff = p1.leverage - p2.leverage;   // positive = p1 wins
  const winner = diff > 0 ? 1 : (diff < 0 ? 2 : 0);
  const absLev = Math.abs(diff);

  // Map leverage diff to a "push distance". absLev can be large with accumulated leverage.
  const intensity = Math.min(1, absLev / 150);

  // Winner takes the full briefcase. Leverage determines who wins, not the size of the payout.
  const payout = winner ? state.briefcaseValue : 0;

  // ---- Animate hands ----
  // We'll position by left/right percentages.
  if (winner === 1) {
    // P1 moves in strongly; P2 gets pushed back to their own side then "reaches in" at a weaker angle
    els.handP1.style.left = (35 + 5 * (1 - intensity)) + "%";  // toward center
    els.handP2.style.right = (30 + 20 * intensity) + "%";       // pushed back to right side
    els.handP2.style.transform = `scaleX(-1) rotate(${10 * intensity}deg)`;
    els.briefcase.style.transform = `translateX(calc(-50% + ${15 * intensity}%))`; // briefcase slides toward P1
  } else if (winner === 2) {
    els.handP2.style.right = (35 + 5 * (1 - intensity)) + "%";
    els.handP1.style.left = (30 + 20 * intensity) + "%";
    els.handP1.style.transform = `rotate(${-10 * intensity}deg)`;
    els.briefcase.style.transform = `translateX(calc(-50% - ${15 * intensity}%))`;
  } else {
    // Draw: both hands meet in the middle equally
    els.handP1.style.left = "38%";
    els.handP2.style.right = "38%";
  }

  // ---- Banner + cash ----
  setTimeout(() => {
    let bannerText, color;
    if (winner === 1) {
      bannerText = `PLAYER 1 WINS THE BRIEFCASE  +$${payout}`;
      color = "var(--p1-color)";
      state.players[0].cash += payout;
    } else if (winner === 2) {
      bannerText = `PLAYER 2 WINS THE BRIEFCASE  +$${payout}`;
      color = "var(--p2-color)";
      state.players[1].cash += payout;
    } else {
      bannerText = "STALEMATE — NO DEAL";
      color = "#555";
    }
    // Penalty for finishing the round with negative leverage
    for (const p of state.players) {
      if (p.leverage < 0) {
        const loss = Math.min(p.cash, Math.min(30, Math.floor(Math.abs(p.leverage) / 5)));
        p.cash -= loss;
      }
    }

    els.dealBannerText.textContent = bannerText;
    els.dealBanner.style.background =
      `linear-gradient(to bottom, ${color}, #000)`;
    els.dealBanner.style.color = "white";
    els.dealBanner.classList.add("shown");

    // Fly money effect
    if (winner) flyMoney(winner, payout);

    updateHUD();
  }, 900);

  // ---- Move on ----
  setTimeout(() => {
    state.phase = "between";
    els.dealBanner.classList.remove("shown");
    setTimeout(() => {
      if (state.roundType === "strikes") {
        const strikeLimitReached = state.players.some(p => p.strikes >= 3);
        if (!strikeLimitReached && state.roundQuestions < 27) {
          startNextQuestionSameRound();
          return;
        }
      } else if (state.roundQuestions < 10) {
        startNextQuestionSameRound();
        return;
      }
      nextRound();
    }, 900);
  }, 3200);
}

function flyMoney(winner, amount) {
  // Emit N little money bills from briefcase to winner's panel
  const bills = Math.min(8, Math.max(3, Math.round(amount / 30)));
  const briefRect = els.briefcase.getBoundingClientRect();
  const targetRect = (winner === 1 ? els.panelP1 : els.panelP2).getBoundingClientRect();
  const areaRect = els.dealArea.getBoundingClientRect();

  for (let i = 0; i < bills; i++) {
    const bill = document.createElement("div");
    bill.className = "money-fly";
    bill.textContent = "$";
    const startX = briefRect.left - areaRect.left + 20;
    const startY = briefRect.top - areaRect.top + 10;
    bill.style.left = startX + "px";
    bill.style.top = startY + "px";
    els.dealArea.appendChild(bill);

    // Target roughly the center of the cash counter
    const endX = (winner === 1 ? 30 : areaRect.width - 70) + (Math.random() - 0.5) * 30;
    const endY = -40 + Math.random() * 20;

    bill.animate([
      { left: startX + "px", top: startY + "px", opacity: 1, transform: "scale(1)" },
      { opacity: 1, offset: 0.7 },
      { left: endX + "px", top: endY + "px", opacity: 0, transform: "scale(0.5)" }
    ], {
      duration: 900 + Math.random() * 300,
      delay: i * 80,
      easing: "cubic-bezier(0.4, 0.0, 0.6, 1)",
      fill: "forwards"
    });
    setTimeout(() => bill.remove(), 1500 + i * 80);
  }
}

// ============================================================
// HUD
// ============================================================
function updateHUD() {
  $("cash-p1").textContent = state.players[0].cash;
  $("cash-p2").textContent = state.players[1].cash;
  $("leverage-p1").textContent = state.players[0].leverage;
  $("leverage-p2").textContent = state.players[1].leverage;
  renderStrikes(1);
  renderStrikes(2);
  if (state.briefcaseValue) {
    if (els.briefcaseAmount) els.briefcaseAmount.textContent = "$" + state.briefcaseValue;
    const hudEl = $("briefcase-hud");
    if (hudEl) hudEl.textContent = "BRIEFCASE  $" + state.briefcaseValue;
  }
  // Highlight who's "active" (has the most leverage this round)
  els.panelP1.classList.toggle("active", state.players[0].leverage > state.players[1].leverage && state.players[0].leverage > 0);
  els.panelP2.classList.toggle("active", state.players[1].leverage > state.players[0].leverage && state.players[1].leverage > 0);
}

function renderStrikes(pNum) {
  const wrap = $("strikes-p" + pNum);
  const tot = state.players[pNum - 1].strikes + (state.players[pNum - 1].strikesThisRound || 0);
  const kids = wrap.querySelectorAll(".strike-x");
  kids.forEach((k, i) => {
    k.classList.toggle("active", i < Math.min(3, tot));
  });
}

// ============================================================
// MODAL
// ============================================================
function showModal({ title, subtitle, detail, actions }) {
  els.modalTitle.textContent = title;
  els.modalSub.textContent = subtitle || "";
  els.modalDetail.textContent = detail || "";
  els.modalActions.innerHTML = "";
  for (const a of (actions || [])) {
    const b = document.createElement("button");
    b.className = "luna-btn" + (a.primary ? " primary" : "");
    b.textContent = a.label;
    b.addEventListener("click", a.onclick);
    els.modalActions.appendChild(b);
  }
  // Set modal focus to the first action and show it
  modalFocus = 0;
  updateModalFocus();
  els.modal.classList.add("active");
}
function hideModal() {
  els.modal.classList.remove("active");
  // clear focused state on buttons
  if (els.modalActions) {
    const btns = els.modalActions.querySelectorAll('button');
    btns.forEach(b => b.classList.remove('focused'));
  }
}

function showHelpModal() {
  const detail = [
    'Controls:',
    'Player 1: 1 2 3 4 (A/B/C/D)',
    'Player 2: 7 8 9 0 (A/B/C/D)',
    'Escape: return to main menu',
    '',
    'Round types:',
    '- Buzz-In: First correct answer wins the entire pot. Wrong buzz locks you out for that question.',
    '- Simultaneous: Players lock in answers secretly; both reveal together. Correct answers earn leverage.',
    '- Three Strikes: Wrong answers add strikes. The round continues with new questions until someone reaches 3 strikes (locked out). Correct answers remove one of your strikes.',
    '',
    'Leverage & payout:',
    '- Each round has a briefcase worth a set amount (shown at round start and on the table).',
    '- Leverage accumulates across all questions in a round. The player with more leverage wins the full briefcase.',
    '- Negative leverage costs you cash at round end (up to $30). Play sharp to avoid going negative.',
    '',
    'Tips:',
    '- Simultaneous picks are hidden until reveal; press indicators appear only after resolution.',
    '- In Three Strikes rounds, be conservative — wrong answers add strikes.'
  ].join('\n');

  showModal({
    title: 'GAME HELP',
    subtitle: 'Controls, rounds, and leverage',
    detail,
    actions: [ { label: 'Close', primary: true, onclick: () => { hideModal(); } } ]
  });
}

// ============================================================
// END OF GAME
// ============================================================
function endGame() {
  state.phase = "idle";
  const p1 = state.players[0].cash;
  const p2 = state.players[1].cash;
  const winner = p1 > p2 ? 1 : (p2 > p1 ? 2 : 0);
  let title, sub;
  if (winner === 0) {
    title = "DRAW";
    sub = `Both hustled their way to $${p1}.`;
  } else {
    title = `PLAYER ${winner} WINS`;
    sub = `$${state.players[winner - 1].cash} vs $${state.players[1 - (winner - 1)].cash}`;
  }
  showModal({
    title, subtitle: sub,
    detail: "Rematch?",
    actions: [
      { label: "▶ Play Again", primary: true, onclick: () => { hideModal(); startGame(); } },
      { label: "Main Menu", onclick: () => { hideModal(); showScene("title"); } }
    ]
  });
}

// Auto-test harness: if URL contains ?autoTest=simul this will simulate a simultaneous round
(function autoTestHarness() {
  try {
    const params = new URLSearchParams(location.search);
    if (!params.has('autoTest')) return;
    const test = params.get('autoTest');
    console.log('AUTO TEST:', test);
    const resultDiv = document.createElement('div');
    resultDiv.style.position = 'fixed';
    resultDiv.style.left = '8px';
    resultDiv.style.bottom = '8px';
    resultDiv.style.zIndex = 9999;
    resultDiv.style.background = 'rgba(0,0,0,0.75)';
    resultDiv.style.color = 'white';
    resultDiv.style.padding = '8px 12px';
    resultDiv.style.borderRadius = '6px';
    resultDiv.style.fontWeight = 'bold';
    resultDiv.textContent = 'AutoTest running...';
    document.body.appendChild(resultDiv);

    if (test === 'simul') {
      // Force a single simultaneous round using the first question in the pool
      state.totalRounds = 1;
      state.round = 0;
      state.question = POOL[0];
      state.roundType = 'simul';
      for (const p of state.players) {
        p.pickedChoice = null; p.lockedOut = false; p.answeredCorrect = false; p.strikesThisRound = 0;
      }
      showScene('game');
      // Start the question phase
      beginQuestion();

      // Simulate P1 then P2 picking different choices
      setTimeout(() => {
        handlePlayerInput(1, 0); // P1 picks choice 0
        // Check press indicators remain hidden
        const p1dot = document.querySelector('.press-dot.p1.shown');
        const p2dot = document.querySelector('.press-dot.p2.shown');
        const beforeHidden = !p1dot && !p2dot;
        console.log('Before reveal, indicators shown?', !!p1dot, !!p2dot);
        resultDiv.textContent = 'Before reveal hidden: ' + beforeHidden;

        handlePlayerInput(2, 1); // P2 picks choice 1
        const p1dot2 = document.querySelector('.press-dot.p1.shown');
        const p2dot2 = document.querySelector('.press-dot.p2.shown');
        const stillHidden = !p1dot2 && !p2dot2;
        console.log('After both pick, indicators shown?', !!p1dot2, !!p2dot2);
        resultDiv.textContent = 'Before reveal hidden: ' + (beforeHidden && stillHidden);
      }, 200);

      // After resolution, ensure indicators are revealed
      setTimeout(() => {
        // give resolution time to run (resolveQuestion schedules a reveal)
        setTimeout(() => {
          const p1Shown = !!document.querySelector('.press-dot.p1.shown');
          const p2Shown = !!document.querySelector('.press-dot.p2.shown');
          const pass = p1Shown && p2Shown;
          console.log('After reveal, indicators shown?', p1Shown, p2Shown);
          if (pass) {
            resultDiv.style.background = 'green';
            resultDiv.textContent = 'AUTO TEST PASS — simultaneous picks hidden until reveal';
          } else {
            resultDiv.style.background = '#800000';
            resultDiv.textContent = 'AUTO TEST FAIL — picks visible prematurely';
          }
        }, 900);
      }, 900);
    }
  } catch (err) {
    console.error('AutoTest error', err);
  }
})();
